export const RELEVANT_STIMULAE = [
    {text: 'Доран', isAnagram: true, isRelevant: true },
    {text: 'Голур', isAnagram: false, isRelevant: true },
    {text: 'Цясем', isAnagram: true, isRelevant: true },
    {text: 'Йизеп', isAnagram: false, isRelevant: true },
    {text: 'Тевос', isAnagram: true, isRelevant: true },
    {text: 'Ройан', isAnagram: false, isRelevant: true },
    {text: 'Целап', isAnagram: true, isRelevant: true },
    {text: 'Гопюр', isAnagram: false, isRelevant: true },
    {text: 'Телоп', isAnagram: true, isRelevant: true },
    {text: 'Редиб', isAnagram: false, isRelevant: true },
    {text: 'Йорег', isAnagram: true, isRelevant: true },
    {text: 'Товил', isAnagram: false, isRelevant: true },
    {text: 'Доваз', isAnagram: true, isRelevant: true },
    {text: 'Межат', isAnagram: false, isRelevant: true },
    {text: 'Дохыв', isAnagram: true, isRelevant: true },
    {text: 'Тулаж', isAnagram: false, isRelevant: true },
    {text: 'Кижум', isAnagram: true, isRelevant: true },
    {text: 'Жебас', isAnagram: false, isRelevant: true },
    {text: 'Равот', isAnagram: true, isRelevant: true },
    {text: 'Когас', isAnagram: false, isRelevant: true },
    {text: 'Сурив', isAnagram: true, isRelevant: true },
    {text: 'Добаг', isAnagram: false, isRelevant: true },
    {text: 'Кошем', isAnagram: true, isRelevant: true },
    {text: 'Тежум', isAnagram: false, isRelevant: true },
]

export const DISTRACTIONS = [
    {text: 'Зибак', isRelevant: false},
    {text: 'Зуфос', isRelevant: false},
    {text: 'Кобес', isRelevant: false}, 
    {text: 'Набер', isRelevant: false},
    {text: 'Ресуг', isRelevant: false},
    {text: 'Сывер', isRelevant: false},
    {text: 'Кабиз', isRelevant: false},
    {text: 'Софуз', isRelevant: false},
    {text: 'Ребан', isRelevant: false},
    {text: 'Гусер', isRelevant: false},
    {text: 'Ревыс', isRelevant: false},
    {text: 'Себок', isRelevant: false},
    {text: 'Рулог', isRelevant: false},
    {text: 'Цезий', isRelevant: false},
    {text: 'Найор', isRelevant: false},
    {text: 'Рюпог', isRelevant: false},
    {text: 'Бидер', isRelevant: false},
    {text: 'Ливот', isRelevant: false},
    {text: 'Тажем', isRelevant: false},
    {text: 'Жалут', isRelevant: false},
    {text: 'Сабеж', isRelevant: false},
    {text: 'Сагок', isRelevant: false},
    {text: 'Габод', isRelevant: false},
    {text: 'Мужет', isRelevant: false},
]
